build:
  - name: Install Rust and Cargo
    env: {}
    command: >
      curl https://sh.rustup.rs -sSf | sh -s -- -y &&
      export PATH="$HOME/.cargo/bin:$PATH"
  - name: Install Python Dependencies
    env: {}
    command: >
      python -m pip install -r requirements.txt